### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting ',' delimiter:

### ISSUE THREAD

**Issue by Marc-marc-marc** [matkoniecz/osm_bot_abstraction_layer#8]
downloading https://www.openstreetmap.org/relation/18050854
Traceback (most recent call last):
  File "type-associatedstreet-france.py", line 27, in <module>
    main()
  File "type-associatedstreet-france.py", line 11, in main
    run_simple_retagging_task(
  File "/home/marc_marc/pyenv/versions/3.8.20/lib/python3.8/site-packages/osm_bot_abstraction_layer/generic_bot_retagging.py", line 254, in run_simple_retagging_task
    run_actual_edits(packages, is_in_manual_mode, changeset_comment, discussion_url, osm_wiki_documentation_page, edit_element_function, skip_on_nearby_notes)
  File "/home/marc_marc/pyenv/versions/3.8.20/lib/python3.8/site-packages/osm_bot_abstraction_layer/generic_bot_retagging.py", line 215, in run_actual_edits
    process_osm_elements_package(package, is_in_manual_mode, changeset_comment, discussion_url, osm_wiki_documentation_page, edit_element_function, skip_on_nearby_notes)
  File "/home/marc_marc/pyenv/versions/3.8.20/lib/python3.8/site-packages/osm_bot_abstraction_layer/generic_bot_retagging.py", line 117, in process_osm_elements_package
    data = modify_data_locally_and_show_changes(element.get_link(), edit_element_function)
  File "/home/marc_marc/pyenv/versions/3.8.20/lib/python3.8/site-packages/osm_bot_abstraction_layer/generic_bot_retagging.py", line 167, in modify_data_locally_and_show_changes
    data = osm_bot_abstraction_layer.get_and_verify_data(osm_link_to_object, prerequisites)
  File "/home/marc_marc/pyenv/versions/3.8.20/lib/python3.8/site-packages/osm_bot_abstraction_layer/osm_bot_abstraction_layer.py", line 191, in get_and_verify_data
    data = get_data_based_on_object_link(osm_object_url)
  File "/home/marc_marc/pyenv/versions/3.8.20/lib/python3.8/site-packages/osm_bot_abstraction_layer/osm_bot_abstraction_layer.py", line 61, in get_data_based_on_object_link
    return get_data(id, element_type)
  File "/home/marc_marc/pyenv/versions/3.8.20/lib/python3.8/site-packages/osm_bot_abstraction_layer/osm_bot_abstraction_layer.py", line 65, in get_data
    api = get_api('bot_account')
  File "/home/marc_marc/pyenv/versions/3.8.20/lib/python3.8/site-packages/osm_bot_abstraction_layer/osm_bot_abstraction_layer.py", line 16, in get_api
    data = json.load(f)
  File "/home/marc_marc/pyenv/versions/3.8.20/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/marc_marc/pyenv/versions/3.8.20/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/marc_marc/pyenv/versions/3.8.20/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/marc_marc/pyenv/versions/3.8.20/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 5 column 3 (char 76)

**Comment by matkoniecz** [comment]
Can you share code that you used to trigger this?

**Comment by Marc-marc-marc** [comment]
https://github.com/Marc-marc-marc/osm_bot_abstraction_layer/blob/master/fix/type-associatedstreet-france.py

**Comment by matkoniecz** [comment]
sorry

I finally mostly dug out myself from pile of TODO notes and had time to looked into this.

By now neither original query nor modified 

```[date:"2014-09-25T00:00:00Z"][out:xml][timeout:6000];
area[name=France][type=boundary][boundary=administrative][admin_level=2]->.a;
relation[type=associatedstreet](area.a);
out body;>;out skel qt;``` 

is able to trigger this crash.

Sorry for not looking into it earlier but by now it looks not reproducible.

Hopefully it was some transitional Overpass issue?

**Comment by Marc-marc-marc** [comment]
fixed by https://github.com/matkoniecz/osm_bot_abstraction_layer/pull/12
